### ISSUE TITLE
Cannot Find/Install Extension in Visual Studio 2017 RTW

### ISSUE THREAD

**Issue by jdaigle** [madskristensen/ToggleFeatures#3]
### Affected Version

VisualStudio/15.0.0-RTW+26228.4

### Steps to recreate

1. Install Visual Studio 2017 RTW
2. Open Extensions and Updates
3. Click on Online
4. Search for "Disable Solution"
5. The extension is not in the search results

**Comment by NickCraver** [comment]
There's a PR open for this now: #4

**Comment by madskristensen** [comment]
@jdaigle @NickCraver VS2017 support should now be added. Please try the [CI build](http://vsixgallery.com/extension/4ce74140-3f68-4438-92a4-a54afea98179/) to verify it works before I publish to the Marketplace
